### ISSUE TITLE
Update Readme with details about OCR

### ISSUE THREAD

**Issue by devhls** [kfrancis/ocr#11]
It’s useful to know which OCR engine or algorithms are used in this plugin. This information can impact the reliability of the plugin and influence the minimum camera specifications, the maximum distance from the target, and any additional quality or symbol-specific requirements.

**Comment by kfrancis** [comment]
I'll see what I can add. The actual algorithms are from each platform, though I guess I can link to the platform documentation a bit. Since it's abstracted away from the user, I'm not sure how useful it'll be ..
