### ISSUE TITLE
Can I use this repo for WinForm project?

### ISSUE THREAD

**Issue by zydjohnHotmail** [kfrancis/ocr#4]
Hi,
I found your repo, it looks nice. But many of my projects are using WinForms, I need a lot of OpenCvSharp code and some SQL Server database code.  But I also need OCR, I think Windows 10 has built-in OCR support, but not for WinForms project, so I wounder if I can use your repo in my WinForms project.
If yes, then give me a general instructions on how to do this.
Thanks,

**Comment by kfrancis** [comment]
I doubt it, at least not directly (unless it's Maui). Can you access `Windows.Media.OcrEngine`? If so, you might be able to just do the same thing I'm doing for my windows implementation.
